services:
  trader:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_COMMIT_SHA: ${GIT_COMMIT_SHA:-local-dev}

  watcher:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_COMMIT_SHA: ${GIT_COMMIT_SHA:-local-dev}

  ui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_COMMIT_SHA: ${GIT_COMMIT_SHA:-local-dev}
