from enum import Enum

class TradeState(str, Enum):
    PENDING = "PENDING"
    OPEN = "OPEN"
    MODIFYING = "MODIFYING"
    CLOSING = "CLOSING"
    CLOSED = "CLOSED"

class TradeEvent(str, Enum):
    ORDER_SENT = "ORDER_SENT"
    ORDER_ACKNOWLEDGED = "ORDER_ACKNOWLEDGED"
    PRICE_UPDATED = "PRICE_UPDATED"
    MANUAL_CLOSE_REQUESTED = "MANUAL_CLOSE_REQUESTED"
    STOP_LOSS_TRIGGERED = "STOP_LOSS_TRIGGERED"
    TAKE_PROFIT_TRIGGERED = "TAKE_PROFIT_TRIGGERED"
    CLOSE_FILLED = "CLOSE_FILLED"
