services:
  trader:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_COMMIT_SHA: ${GIT_COMMIT_SHA:-local-dev}
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=trader_pass

  watcher:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_COMMIT_SHA: ${GIT_COMMIT_SHA:-local-dev}
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=trader_pass

  ui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_COMMIT_SHA: ${GIT_COMMIT_SHA:-local-dev}
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=trader_pass
